# Fix the candidate's synchronous MUL_MAT_ID gather for token-strided inputs.
# get_rows uses a physical row index; ne11 is the logical lane count, not stride.
set(step_dispatch_original "${step_source}/ggml/src/ggml-cuda/ggml-cuda.cu")
file(SHA256 "${step_dispatch_original}" step_dispatch_original_sha256)
if(NOT step_dispatch_original_sha256 STREQUAL "eee8c85f32f45c47d0f84210d82109598c0dd32c73b3d4605972a62569af7034")
  message(FATAL_ERROR "Review Step routed input stride patch for the changed candidate")
endif()
file(READ "${step_dispatch_original}" step_dispatch)
set(step_stride_anchor "                    ids_to_sorted_host.push_back(i12*ne11 + iex % ne11);")
string(FIND "${step_dispatch}" "${step_stride_anchor}" step_stride_found)
if(step_stride_found EQUAL -1)
  message(FATAL_ERROR "Step routed gather patch site not found")
endif()
string(REPLACE "${step_stride_anchor}" "                    // Flatten physical rows, including padding between tokens.
                    const size_t src1_row = i12 * (nb12 / nb11) + iex % ne11;
                    GGML_ASSERT(src1_row <= INT32_MAX);
                    ids_to_sorted_host.push_back(static_cast<int32_t>(src1_row));" step_dispatch "${step_dispatch}")
set(step_dispatch_generated "${CMAKE_BINARY_DIR}/strata-step35-cuda.cu")
set(step_dispatch_previous "")
if(EXISTS "${step_dispatch_generated}")
  file(READ "${step_dispatch_generated}" step_dispatch_previous)
endif()
if(NOT step_dispatch_previous STREQUAL step_dispatch)
  file(WRITE "${step_dispatch_generated}" "${step_dispatch}")
endif()
file(SHA256 "${step_dispatch_generated}" step_dispatch_generated_sha256)
get_target_property(step_cuda_sources ggml-cuda SOURCES)
set(step_dispatch_sources "${step_cuda_sources}")
list(FILTER step_dispatch_sources INCLUDE REGEX "(^|/)ggml-cuda\\.cu$")
list(LENGTH step_dispatch_sources step_dispatch_count)
if(NOT step_dispatch_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one ggml-cuda.cu translation unit")
endif()
list(REMOVE_ITEM step_cuda_sources ${step_dispatch_sources})
set_property(TARGET ggml-cuda PROPERTY SOURCES "${step_cuda_sources};${step_dispatch_generated}")
set_source_files_properties("${step_dispatch_generated}" TARGET_DIRECTORY ggml-cuda PROPERTIES
  INCLUDE_DIRECTORIES "${step_source}/ggml/src;${step_source}/ggml/src/ggml-cuda")
if(step_patch_set STREQUAL "none")
  set(step_patch_set "cuda-routed-input-strides")
else()
  string(APPEND step_patch_set ",cuda-routed-input-strides")
endif()
