# Step-only generated translation units. Keep the extracted candidate untouched.
function(step_replace_once variable before after)
  string(FIND "${${variable}}" "${before}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Missing Step runtime patch anchor: ${before}")
  endif()
  string(REPLACE "${before}" "" without "${${variable}}")
  # Hash guards pin the entire file; anchors are additionally checked below.
  string(LENGTH "${${variable}}" old_length)
  string(LENGTH "${without}" new_length)
  string(LENGTH "${before}" anchor_length)
  math(EXPR removed "${old_length}-${new_length}")
  if(NOT removed EQUAL anchor_length)
    message(FATAL_ERROR "Expected one Step runtime anchor: ${before}")
  endif()
  string(REPLACE "${before}" "${after}" result "${${variable}}")
  set(${variable} "${result}" PARENT_SCOPE)
endfunction()
function(step_runtime_source target relative expected output)
  set(original "${step_source}/${relative}")
  file(SHA256 "${original}" hash)
  if(NOT hash STREQUAL expected)
    message(FATAL_ERROR "Review Step runtime patch for changed ${relative}")
  endif()
  file(READ "${original}" content)
  if(target STREQUAL "ggml-base")
    set(anchor "static enum ggml_status ggml_backend_sched_compute_splits(ggml_backend_sched_t sched) {")
    step_replace_once(content "${anchor}" "#include \"sync_runtime.inc\"\n${anchor}\n#include \"gpu_only_audit.inc\"\n    StepPlanScope step_scope;")
    step_replace_once(content "                        prev_ids_tensor = ids_tensor;"
      "#include \"pipeline_sched.inc\"\n                        prev_ids_tensor = ids_tensor;")
    step_replace_once(content "        prev_backend_id = split_backend_id;\n    }\n\n    return GGML_STATUS_SUCCESS;"
      "        prev_backend_id = split_backend_id;\n    }\n\n    if (!step_scope.finish()) return GGML_STATUS_FAILED;\n    return GGML_STATUS_SUCCESS;")
    step_replace_once(content "ggml_backend_graph_compute_async(split_backend, &split->graph)" "step_graph_compute(split_backend, &split->graph)")
    step_replace_once(content "ggml_backend_graph_compute_async(split_backend, &gv)" "step_graph_compute(split_backend, &gv)")
    set(anchor "                        ggml_backend_tensor_set_async(split_backend,")
    step_replace_once(content "${anchor}" "                        if (step_sync_mode == 2) {\n                            return step_copy_range(split_backend, input_cpy, input, expert_offset, expert_size_copy + padding_end);\n                        }\n${anchor}")
    set(anchor "                            expert_size_copy + padding_end);\n                    };")
    step_replace_once(content "${anchor}" "                            expert_size_copy + padding_end);\n                        return true;\n                    };")
    step_replace_once(content "                        copy_experts(first_id, last_id);" "                        if (!copy_experts(first_id, last_id)) return GGML_STATUS_FAILED;")
    step_replace_once(content "                    copy_experts(first_id, last_id);" "                    if (!copy_experts(first_id, last_id)) return GGML_STATUS_FAILED;")
    set(anchor "                    // try async copy, but if not possible,")
    step_replace_once(content "${anchor}" "                    if (step_sync_mode && ggml_backend_buffer_is_host(input->buffer) &&\n                        ggml_backend_buffer_get_usage(input->buffer) == GGML_BACKEND_BUFFER_USAGE_WEIGHTS &&\n                        step_expert_weight(input)) {\n                        ++step_sync_stats.rejected_full_copies;\n                        GGML_LOG_ERROR(\"STRATA_STEP refusing full expert tensor copy: %s\\n\", input->name);\n                        return GGML_STATUS_FAILED;\n                    }\n${anchor}")
  else()
    step_replace_once(content "const size_t prefetch_size = prefetch && use_mmap ? -1 : 0;"
      "const size_t prefetch_size = arch_name == \"step35\" ? 0 : (prefetch && use_mmap ? -1 : 0); // Step: demand-page experts")
  endif()
  set(generated "${CMAKE_BINARY_DIR}/${output}")
  set(previous "")
  if(EXISTS "${generated}")
    file(READ "${generated}" previous)
  endif()
  if(NOT previous STREQUAL content)
    file(WRITE "${generated}" "${content}")
  endif()
  get_target_property(sources ${target} SOURCES)
  get_filename_component(name "${relative}" NAME)
  set(matches "${sources}")
  list(FILTER matches INCLUDE REGEX "(^|/)${name}$")
  list(LENGTH matches count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected one ${name} in ${target}")
  endif()
  list(REMOVE_ITEM sources ${matches})
  set_property(TARGET ${target} PROPERTY SOURCES "${sources};${generated}")
  get_filename_component(directory "${original}" DIRECTORY)
  set_source_files_properties("${generated}" TARGET_DIRECTORY ${target} PROPERTIES
    INCLUDE_DIRECTORIES "${directory};${CMAKE_CURRENT_SOURCE_DIR}"
    OBJECT_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/sync_runtime.h;${CMAKE_CURRENT_SOURCE_DIR}/sync_runtime.inc;${CMAKE_CURRENT_SOURCE_DIR}/gpu_only_audit.inc;${CMAKE_CURRENT_SOURCE_DIR}/expert_cache.hpp;${CMAKE_CURRENT_SOURCE_DIR}/pipeline_runtime.inc;${CMAKE_CURRENT_SOURCE_DIR}/pipeline_sched.inc;${CMAKE_CURRENT_SOURCE_DIR}/gpu_trace.hpp")
endfunction()
step_runtime_source(ggml-base ggml/src/ggml-backend.cpp
  a39c4fe81b043c7e8616ebe57afb75d727c692fe3b26c3e9bc2ddde3c6991041 strata-step35-backend.cpp)
step_runtime_source(llama src/llama-model-loader.cpp
  5ef07476310d4678df18a61a6ec0a1ebcbb58c7534ac3c624b9fe0f315a4ab01 strata-step35-loader.cpp)
string(APPEND step_patch_set ",step-sync-selected-copy-gpu-audit-mmap-demand")
string(APPEND step_patch_set ",step-bounded-expert-cache")
string(APPEND step_patch_set ",step-router-lookahead-pipeline")
string(APPEND step_patch_set ",step-prefill-cache-admission")
target_link_libraries(ggml-base PRIVATE CUDA::cudart_static)
target_compile_features(ggml-base PRIVATE cxx_std_17)
target_include_directories(ggml-base PRIVATE "${step_source}/vendor")
