# Hy3-local generated source: propagate load_mtp=false to optional FFN/NextN
# tensors too. Keep the archive and extracted dependency unchanged.
file(READ "${hy3_source}/src/models/hy-v3.cpp" hy3_loader)
set(hy3_begin_anchor "    auto load_block = [&](int i, int flags) {")
set(hy3_end_anchor "    for (int i = 0; i < n_layer; ++i) {")
string(FIND "${hy3_loader}" "${hy3_begin_anchor}" hy3_begin)
string(FIND "${hy3_loader}" "${hy3_end_anchor}" hy3_end)
if(hy3_begin LESS 0 OR hy3_end LESS_EQUAL hy3_begin)
  message(FATAL_ERROR "Hy3 MTP load-flags patch anchors changed")
endif()
math(EXPR hy3_length "${hy3_end} - ${hy3_begin}")
string(SUBSTRING "${hy3_loader}" 0 ${hy3_begin} hy3_prefix)
string(SUBSTRING "${hy3_loader}" ${hy3_begin} ${hy3_length} hy3_block)
string(SUBSTRING "${hy3_loader}" ${hy3_end} -1 hy3_tail)
string(REPLACE "TENSOR_NOT_REQUIRED" "(flags | TENSOR_NOT_REQUIRED)" hy3_block "${hy3_block}")
string(REPLACE "TENSOR_NOT_REQUIRED" "(mtp_flags | TENSOR_NOT_REQUIRED)" hy3_tail "${hy3_tail}")
set(hy3_generated "${CMAKE_BINARY_DIR}/strata-hy3-model.cpp")
set(hy3_patched "${hy3_prefix}${hy3_block}${hy3_tail}")
set(hy3_previous "")
if(EXISTS "${hy3_generated}")
  file(READ "${hy3_generated}" hy3_previous)
endif()
if(NOT hy3_previous STREQUAL hy3_patched)
  file(WRITE "${hy3_generated}" "${hy3_patched}")
endif()
file(SHA256 "${hy3_generated}" hy3_generated_sha256)
get_target_property(hy3_llama_sources llama SOURCES)
set(hy3_original_sources "${hy3_llama_sources}")
list(FILTER hy3_original_sources INCLUDE REGEX "(^|/)hy-v3\\.cpp$")
list(LENGTH hy3_original_sources hy3_source_count)
if(NOT hy3_source_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one Hy3 model translation unit")
endif()
list(REMOVE_ITEM hy3_llama_sources ${hy3_original_sources})
set_property(TARGET llama PROPERTY SOURCES "${hy3_llama_sources};${hy3_generated}")
set_source_files_properties("${hy3_generated}" TARGET_DIRECTORY llama PROPERTIES
  INCLUDE_DIRECTORIES "${hy3_source}/src/models")
set(hy3_patch_set "hy3-mtp-load-flags")
