# Fix the candidate's synchronous MUL_MAT_ID gather for token-strided inputs.
# get_rows uses a physical row index; ne11 is the logical lane count, not stride.
set(hy3_dispatch_original "${hy3_source}/ggml/src/ggml-cuda/ggml-cuda.cu")
file(SHA256 "${hy3_dispatch_original}" hy3_dispatch_original_sha256)
if(NOT hy3_dispatch_original_sha256 STREQUAL "eee8c85f32f45c47d0f84210d82109598c0dd32c73b3d4605972a62569af7034")
  message(FATAL_ERROR "Review Hy3 routed input stride patch for the changed candidate")
endif()
file(READ "${hy3_dispatch_original}" hy3_dispatch)
set(hy3_stride_anchor "                    ids_to_sorted_host.push_back(i12*ne11 + iex % ne11);")
string(FIND "${hy3_dispatch}" "${hy3_stride_anchor}" hy3_stride_found)
if(hy3_stride_found EQUAL -1)
  message(FATAL_ERROR "Hy3 routed gather patch site not found")
endif()
string(REPLACE "${hy3_stride_anchor}" "                    // Flatten physical rows, including padding between tokens.
                    const size_t src1_row = i12 * (nb12 / nb11) + iex % ne11;
                    GGML_ASSERT(src1_row <= INT32_MAX);
                    ids_to_sorted_host.push_back(static_cast<int32_t>(src1_row));" hy3_dispatch "${hy3_dispatch}")
set(hy3_dispatch_generated "${CMAKE_BINARY_DIR}/strata-hy3-cuda.cu")
set(hy3_dispatch_previous "")
if(EXISTS "${hy3_dispatch_generated}")
  file(READ "${hy3_dispatch_generated}" hy3_dispatch_previous)
endif()
if(NOT hy3_dispatch_previous STREQUAL hy3_dispatch)
  file(WRITE "${hy3_dispatch_generated}" "${hy3_dispatch}")
endif()
file(SHA256 "${hy3_dispatch_generated}" hy3_dispatch_generated_sha256)
get_target_property(hy3_cuda_sources ggml-cuda SOURCES)
set(hy3_dispatch_sources "${hy3_cuda_sources}")
list(FILTER hy3_dispatch_sources INCLUDE REGEX "(^|/)ggml-cuda\\.cu$")
list(LENGTH hy3_dispatch_sources hy3_dispatch_count)
if(NOT hy3_dispatch_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one ggml-cuda.cu translation unit")
endif()
list(REMOVE_ITEM hy3_cuda_sources ${hy3_dispatch_sources})
set_property(TARGET ggml-cuda PROPERTY SOURCES "${hy3_cuda_sources};${hy3_dispatch_generated}")
set_source_files_properties("${hy3_dispatch_generated}" TARGET_DIRECTORY ggml-cuda PROPERTIES
  INCLUDE_DIRECTORIES "${hy3_source}/ggml/src;${hy3_source}/ggml/src/ggml-cuda")
if(hy3_patch_set STREQUAL "none")
  set(hy3_patch_set "cuda-routed-input-strides")
else()
  string(APPEND hy3_patch_set ",cuda-routed-input-strides")
endif()
