# Fix the candidate's synchronous MUL_MAT_ID gather for token-strided inputs.
# get_rows uses a physical row index; ne11 is the logical lane count, not stride.
set(mimo_dispatch_original "${mimo_source}/ggml/src/ggml-cuda/ggml-cuda.cu")
file(SHA256 "${mimo_dispatch_original}" mimo_dispatch_original_sha256)
if(NOT mimo_dispatch_original_sha256 STREQUAL "eee8c85f32f45c47d0f84210d82109598c0dd32c73b3d4605972a62569af7034")
  message(FATAL_ERROR "Review MiMo routed input stride patch for the changed candidate")
endif()
file(READ "${mimo_dispatch_original}" mimo_dispatch)
set(mimo_stride_anchor "                    ids_to_sorted_host.push_back(i12*ne11 + iex % ne11);")
string(FIND "${mimo_dispatch}" "${mimo_stride_anchor}" mimo_stride_found)
if(mimo_stride_found EQUAL -1)
  message(FATAL_ERROR "MiMo routed gather patch site not found")
endif()
string(REPLACE "${mimo_stride_anchor}" "                    // Flatten physical rows, including padding between tokens.
                    const size_t src1_row = i12 * (nb12 / nb11) + iex % ne11;
                    GGML_ASSERT(src1_row <= INT32_MAX);
                    ids_to_sorted_host.push_back(static_cast<int32_t>(src1_row));" mimo_dispatch "${mimo_dispatch}")
set(mimo_dispatch_generated "${CMAKE_BINARY_DIR}/strata-mimo2-cuda.cu")
set(mimo_dispatch_previous "")
if(EXISTS "${mimo_dispatch_generated}")
  file(READ "${mimo_dispatch_generated}" mimo_dispatch_previous)
endif()
if(NOT mimo_dispatch_previous STREQUAL mimo_dispatch)
  file(WRITE "${mimo_dispatch_generated}" "${mimo_dispatch}")
endif()
file(SHA256 "${mimo_dispatch_generated}" mimo_dispatch_generated_sha256)
get_target_property(mimo_cuda_sources ggml-cuda SOURCES)
set(mimo_dispatch_sources "${mimo_cuda_sources}")
list(FILTER mimo_dispatch_sources INCLUDE REGEX "(^|/)ggml-cuda\\.cu$")
list(LENGTH mimo_dispatch_sources mimo_dispatch_count)
if(NOT mimo_dispatch_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one ggml-cuda.cu translation unit")
endif()
list(REMOVE_ITEM mimo_cuda_sources ${mimo_dispatch_sources})
set_property(TARGET ggml-cuda PROPERTY SOURCES "${mimo_cuda_sources};${mimo_dispatch_generated}")
set_source_files_properties("${mimo_dispatch_generated}" TARGET_DIRECTORY ggml-cuda PROPERTIES
  INCLUDE_DIRECTORIES "${mimo_source}/ggml/src;${mimo_source}/ggml/src/ggml-cuda")
if(mimo_patch_set STREQUAL "none")
  set(mimo_patch_set "cuda-routed-input-strides")
else()
  string(APPEND mimo_patch_set ",cuda-routed-input-strides")
endif()
