# Fix the candidate's synchronous MUL_MAT_ID gather for token-strided inputs.
# get_rows uses a physical row index; ne11 is the logical lane count, not stride.
set(mm27_dispatch_original "${mm27_source}/ggml/src/ggml-cuda/ggml-cuda.cu")
file(SHA256 "${mm27_dispatch_original}" mm27_dispatch_original_sha256)
if(NOT mm27_dispatch_original_sha256 STREQUAL "eee8c85f32f45c47d0f84210d82109598c0dd32c73b3d4605972a62569af7034")
  message(FATAL_ERROR "Review MiniMax routed input stride patch for the changed candidate")
endif()
file(READ "${mm27_dispatch_original}" mm27_dispatch)
set(mm27_stride_anchor "                    ids_to_sorted_host.push_back(i12*ne11 + iex % ne11);")
string(FIND "${mm27_dispatch}" "${mm27_stride_anchor}" mm27_stride_found)
if(mm27_stride_found EQUAL -1)
  message(FATAL_ERROR "MiniMax routed gather patch site not found")
endif()
string(REPLACE "${mm27_stride_anchor}" "                    // Flatten physical rows, including padding between tokens.
                    const size_t src1_row = i12 * (nb12 / nb11) + iex % ne11;
                    GGML_ASSERT(src1_row <= INT32_MAX);
                    ids_to_sorted_host.push_back(static_cast<int32_t>(src1_row));" mm27_dispatch "${mm27_dispatch}")
set(mm27_dispatch_generated "${CMAKE_BINARY_DIR}/strata-mm27-cuda.cu")
set(mm27_dispatch_previous "")
if(EXISTS "${mm27_dispatch_generated}")
  file(READ "${mm27_dispatch_generated}" mm27_dispatch_previous)
endif()
if(NOT mm27_dispatch_previous STREQUAL mm27_dispatch)
  file(WRITE "${mm27_dispatch_generated}" "${mm27_dispatch}")
endif()
file(SHA256 "${mm27_dispatch_generated}" mm27_dispatch_generated_sha256)
get_target_property(mm27_cuda_sources ggml-cuda SOURCES)
set(mm27_dispatch_sources "${mm27_cuda_sources}")
list(FILTER mm27_dispatch_sources INCLUDE REGEX "(^|/)ggml-cuda\\.cu$")
list(LENGTH mm27_dispatch_sources mm27_dispatch_count)
if(NOT mm27_dispatch_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one ggml-cuda.cu translation unit")
endif()
list(REMOVE_ITEM mm27_cuda_sources ${mm27_dispatch_sources})
set_property(TARGET ggml-cuda PROPERTY SOURCES "${mm27_cuda_sources};${mm27_dispatch_generated}")
set_source_files_properties("${mm27_dispatch_generated}" TARGET_DIRECTORY ggml-cuda PROPERTIES
  INCLUDE_DIRECTORIES "${mm27_source}/ggml/src;${mm27_source}/ggml/src/ggml-cuda")
if(mm27_patch_set STREQUAL "none")
  set(mm27_patch_set "cuda-routed-input-strides")
else()
  string(APPEND mm27_patch_set ",cuda-routed-input-strides")
endif()
